config/urls.py
from art.views import (
    add_new_art_object,
    current_page_for_obj,
    delete_art_object,
    show_all_from_art_model
)
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from search.views import Search
from user.views import (
    change_email,
    change_password,
    change_portfolio_page,
    change_portfolio_picture,
    have_not_permission,
    register,
    success_change,
    support,
    user_login,
    user_logout,
    user_personal_page,
)


urlpatterns = [
    path('add/', add_new_art_object, name='add'),
    path('admin/', admin.site.urls, name='admin'),
    path('art/<str:object_id>/', current_page_for_obj, name='current_page_for_obj'),
    path('art/delete/<str:object_id>/', delete_art_object, name='delete'),
    path('personalpage/changeimg/', change_portfolio_picture, name='change_portfolio_picture'),
    path('personalpage/changeemail/', change_email, name='change_email'),
    path('personalpage/changepassword/', change_password, name='change_password'),
    path('personalpage/changepage/', change_portfolio_page, name='change_portfolio_page'),
    path('personalpage/logout/', user_logout, name='user_logout'),
    path('personalpage/success', success_change, name='success_change'),
    path('personalpage/', user_personal_page, name='personal_page'),
    url(r'^login/$', user_login, name='login'),
    url(r'^registration/$', register, name='register'),
    path('permissionerror/', have_not_permission, name='have_not_permission'),
    path('support/', support, name='support'),
    path('search/', Search.as_view(), name = 'search'),
    path('', show_all_from_art_model, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfileInfo(models.Model):
    ''' User model '''

    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    portfolio_page = models.URLField(blank=True)
    portfolio_picture = models.ImageField(blank=True)

    def __str__(self):
        return self.user.username

user/forms.py
from .models import UserProfileInfo
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    ''' Form for create a username, password and email fields for User '''

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):
    ''' Form for create a portfolio_page, portfolio_picture fields for User '''

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_page', 'portfolio_picture')


class ChangePortfolioPictureForm(forms.ModelForm):
    ''' Form for change a portfolio picture for User '''

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_picture',)


class ChangePortfolioPageForm(forms.ModelForm):
    ''' Form for change a portfolio page for User '''

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_page',)


class ChangeEmailForm(forms.ModelForm):
    ''' Form for change a email for User '''

    class Meta():
        model = User
        fields = ('email',)

user/views.py
from .forms import (
    ChangeEmailForm,
    ChangePortfolioPageForm,
    ChangePortfolioPictureForm,
)
from .services.user_services import (
    after_true_method_verification_for_user_login,
    take_all_users_and_give_to_page,
    validation_and_work_with_info,
    validation_and_work_with_password_change_form,
    work_with_email_change_form,
    work_with_portfolio_page_change_form,
    work_with_portfolio_picture_change_form,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
)
from django.shortcuts import render
from django.urls import reverse


@login_required
def special(request):
    ''' Controller for telling to User
    that he is authorized '''

    return render(request, 'logged_in.html', {})

@login_required
def user_logout(request):
    ''' Controller for logout '''

    logout(request)

    return HttpResponseRedirect('/')

def register(request):
    ''' Controller for registration page '''

    if request.user.is_authenticated:
        return special(request)

    else:
        registered = False

        context = validation_and_work_with_info(request, registered)

        return render(request, 'registration.html', context)

def user_login(request):
    ''' Controller for login page '''

    if request.user.is_authenticated:
        return special(request)

    else:
        if request.method == 'POST':
            return after_true_method_verification_for_user_login(request)

        else:
            return render(request, 'login.html', {})

@login_required
def user_personal_page(request):
    ''' Controller for show or change personal info about Users '''

    context = take_all_users_and_give_to_page(request)

    return render(request, 'personal_page.html', context)

def have_not_permission(request):
    ''' Controller for tell the User that is have not
    a permissions for add new objects '''

    return render(request, 'permissionerror.html', {})

@login_required
def change_portfolio_picture(request):
    ''' Controller for portfolio picture changer '''

    if request.method == 'POST':
        return work_with_portfolio_picture_change_form(request)

    else:
        change_form = ChangePortfolioPictureForm()

    context = { 'change_form': change_form }

    return render(request, 'change_portfolio_picture.html', context)

@login_required
def change_email(request):
    ''' Controller for email changer '''

    if request.method == 'POST':
        return work_with_email_change_form(request)

    else:
        change_form = ChangeEmailForm()

    context = { 'change_form': change_form }

    return render(request, 'change_email.html', context)

@login_required
def change_password(request):
    ''' Controller for password changer '''

    return validation_and_work_with_password_change_form(request)

@login_required
def change_portfolio_page(request):
    ''' Controller for portfolio picture changer '''

    if request.method == 'POST':
        return work_with_portfolio_page_change_form(request)

    else:
        change_form = ChangePortfolioPageForm()

    context = { 'change_form': change_form }

    return render(request, 'change_portfolio_page.html', context)

def success_change(request):
    ''' Controller for telling to User that a
    change password was completed '''

    return render(request, 'success_change.html', {})

def support(request):
    ''' Controller for support page '''

    return render(request, 'support.html', {})

user/templates/change_email.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

	<head>
	  <meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=`, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
		<title>ArtProject</title>
	</head>

	<body>

		<form enctype="multipart/form-data" method="POST" class="form">
			{% csrf_token %}

			<h1 class="form-title">Change Email</h1>

      <div class="form-group">
        <input type="email" name="email" class="form-input" placeholder=" " id="id_email">
        <label class="form-lable">Email</label>
      </div>

			<input type="submit" name="" value="Change" class="form-button">

      {% for message in messages %}
      	<h3 class="form_massage">{{ message }}</h3>
    	{% endfor %}

		</form>



	</body>

</html>

user/templates/change_password_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=`, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
		<title>ArtProject</title>
	</head>

	<body>

		<form enctype="multipart/form-data" method="POST" class="form">
			{% csrf_token %}

			<h1 class="form-title">Change Password</h1>

      <div class="form-group">
				<input type="password" name="old_password" autocomplete="current-password" autofocus required class="form-input" placeholder=" ">
				<label class="form-lable">Old password</label>
			</div>

			<div class="form-group">
				<input type="password" name="new_password1" autocomplete="new-password" required class="form-input" placeholder=" ">
				<label class="form-lable">Password</label>
			</div>

      <div class="form-group">
				<input type="password" name="new_password2" autocomplete="new-password" required class="form-input" placeholder=" ">
				<label class="form-lable">Password</label>
			</div>

			<input type="submit" name="" value="Change" class="form-button">

			{% for message in messages %}
      	<h3 class="form_massage">{{ message }}</h3>
    	{% endfor %}

			{% for field in change_form %}
				{% if field.errors %}
					{{ field.errors }}
				{% endif %}
			{% endfor %}

			<h3>New password mast have a:</h3>

			{% for field in change_form %}
					{{ field.help_text | safe }}
			{% endfor %}

		</form>



	</body>

</html>

user/templates/change_portfolio_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=`, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
		<title>ArtProject</title>
	</head>

	<body>

		<form enctype="multipart/form-data" method="POST" class="form">
			{% csrf_token %}

			<h1 class="form-title">Change Portfolio Page</h1>

      <div class="form-group">
        <input type="url" name="portfolio_page" required class="form-input" placeholder=" " id="id_portfolio_page">
        <label class="form-lable">Portfolio page</label>
      </div>

			<input type="submit" name="" value="Change" class="form-button">

      {% for message in messages %}
      	<h3 class="form_massage">{{ message }}</h3>
    	{% endfor %}

		</form>



	</body>

</html>

user/templates/change_portfolio_picture.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=`, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
		<title>ArtProject</title>
	</head>

	<body>

		<form enctype="multipart/form-data" method="POST" class="form">
			{% csrf_token %}

			<h1 class="form-title">Change Profile Picture</h1>

      <div class="form-pic">
        <label class="form-table">Profile picture:</label>
        <input type="file" name="portfolio_picture" accept="image/*" required id="id_portfolio_picture" style="margin-bottom:25px;">
      </div>

			<input type="submit" name="" value="Change" class="form-button">

      {% for message in messages %}
      	<h3 class="form_massage">{{ message }}</h3>
    	{% endfor %}

		</form>



	</body>

</html>

user/templates/logged_in.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="{% static 'css/permissionerror.css' %}" />
  <title>Error!</title>
</head>

<body>

  <div class="container">
    <div class="content">
      <div class="image__block">
        <img class="image" src="{% static 'img/Error.jpg' %}" alt="">
      </div>
      <div class="text__block">
        <div class="tittle">
          Oops!
        </div>
        <p class="text">
          You are logged in.
        </p>
      </div>
    </div>
      <div class="btn">
        <a href="/" class="neon__btn">Home</a>
      </div>
  </div>

</body>

</html>

user/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=`, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'css/login_style.css' %}">
		<title>Login form</title>
	</head>

	<body>

		<form method="POST" class="form" action="{% url 'login' %}">
			{% csrf_token %}

			<h1 class="form-title">Login form</h1>

			<div class="form-group">
				<input type="text" name="username" class="form-input" placeholder=" ">
				<label class="form-lable">Username</label>
			</div>

			<div class="form-group">
				<input type="password" name="password" class="form-input" placeholder=" ">
				<label class="form-lable">Password</label>
			</div>

			<input type="submit" name="" value="Login" class="form-button">

			<a href="/" class="form-button" style="text-decoration:none; text-align:center;">Main Page</a>

		</form>
	</body>

</html>

user/templates/loginerror.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="{% static 'css/permissionerror.css' %}" />
  <title>Error!</title>
</head>

<body>

  <div class="container">
    <div class="content">
      <div class="image__block">
        <img class="image" src="{% static 'img/Error.jpg' %}" alt="">
      </div>
      <div class="text__block">
        <div class="tittle">
          Oops!
        </div>
        <p class="text">
          Invalid login details given!
        </p>
      </div>
    </div>
      <div class="btn">
        <a href="/" class="neon__btn">Home</a>
      </div>
  </div>

</body>

</html>

user/templates/permissionerror.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="{% static 'css/permissionerror.css' %}" />
  <title>Error!</title>
</head>

<body>

  <div class="container">
    <div class="content">
      <div class="image__block">
        <img class="image" src="{% static 'img/Error.jpg' %}" alt="">
      </div>
      <div class="text__block">
        <div class="tittle">
          Oops!
        </div>
        <p class="text">
          For do it you must have the permissions!
        </p>
      </div>
    </div>
      <div class="btn">
        <a href="/" class="neon__btn">Home</a>
      </div>
  </div>

</body>

</html>

user/templates/personal_page.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>ArtProject</title>
    <link rel="stylesheet" href="{% static 'css/main_blocks/header_and_footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/personal_page.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa">
  </head>
  <body>
    <div class="container">
      <header class="header">
          <div class="header_block-logo">
              <a href="/" class="header_link"><img src="{% static 'img/logo.png' %}" class="link_img"></a>
          </div>

          <div class="header_block-navigation-bar">
            <nav class="header_navigation">
                <a href="/" class="navigation_a">Main</a>
                {% if user.is_authenticated %}
                  {% if user.is_staff %}
                    <a href="/add/" class="navigation_a">Add object</a>
                    <a href="/admin/" class="navigation_a">Admin Panel</a>
                  {% endif %}
                  <a href="/personalpage/" class="navigation_a">Personal Page</a>
                {% else %}
                  <a href="/login/" class="navigation_a">Log In</a>
                  <a href="/registration/" class="navigation_a">Sing Up</a>
                {% endif %}
                <a href="/support/" class="navigation_a">Support</a>
            </nav>
          </div>
      </header>

      <article class="content">

          {% for current_user in all_users %}
            {% if user == current_user.user %}

              {% if current_user.portfolio_picture %}
                <img src="{{ current_user.portfolio_picture.url }}" class="content_image">
              {% else %}
                <img src="{% static 'img/user_without_image.jpg' %}" class="content_image">
              {% endif %}
              <h1 class="content_username">Welcome to the club, <span class="span_username">{{ user.username }}</span> </h1>

              <div class="content_main">

                <p class="main_text-for-objects">Email:</p>
                <p class="main_email">{{ user.email }}</p>

                <p class="main_text-for-objects">Portfolio Page:</p>
                <a href="{{ current_user.portfolio_page }}" class="main_portfolio-page">{{ current_user.portfolio_page }}</a>

            </div>

            {% endif %}
          {% endfor %}

          <div class="content_control-buttons">
            <a class="control-buttons_button" href="/personalpage/changeimg/">Change Portfolio Image</a>
            <a class="control-buttons_button" href="/personalpage/changeemail/">Change Email</a>
            <a class="control-buttons_button" href="/personalpage/changepassword/">Change Password</a>
            <a class="control-buttons_button" href="/personalpage/changepage/">Change Portfolio Page</a>
            <a class="control-buttons_button" href="/personalpage/logout/">Logout</a>
          </div>

      </article>

    </div>
  </body>
</html>

user/templates/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/registration_style.css' %}">
  <title>Register form</title>
</head>

<body>

  <form enctype="multipart/form-data" method="POST" class="form">
    {% csrf_token %}

    <h1 class="form-title">Registration</h1>

    <div class="form-group">
      <input type="text" name="username" required class="form-input" placeholder=" " id="id_username">
      <label class="form-lable">Username</label>
    </div>

    <div class="form-group">
      <input type="password" name="password" required class="form-input" placeholder=" " id="id_password">
      <label class="form-lable">Password</label>
    </div>

    <div class="form-group">
      <input type="email" name="email" class="form-input" placeholder=" " id="id_email">
      <label class="form-lable">Email</label>
    </div>

    <div class="form-group">
      <input type="url" name="portfolio_page" class="form-input" placeholder=" " id="id_portfolio_page">
      <label class="form-lable">Portfolio page</label>
    </div>

    <div class="form-pic">
      <label class="form-table">Profile picture:</label>
      <input type="file" name="portfolio_picture" accept="image/*" id="id_portfolio_picture" style="margin-bottom:25px;">
    </div>

    <button type="submit" name="" value="Register" class="form-button" style="margin-bottom: 25px;">Create</button>

    <a href="/" class="form-button" style="text-decoration:none; text-align:center;">Main Page</a>

  </form>
</body>

</html>

user/templates/success_change.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="{% static 'css/success_change.css' %}" />
  <title>Successful created a new password</title>
</head>

  <body>
  <div class="container">
    <div class="content">
        <img class="image" src="{% static 'img/Success.svg' %}" alt="Success">
      <div class="text__block">
        <div class="tittle">Success!</div>
        <p class="sub__tittle">
          Your info has been successfully changed ;-)
        </p>
      </div>
      <div class="button">
        <a href="/personalpage/" class="button__home">Home</a>
      </div>
    </div>
  </div>
  </body>

</html>

user/templates/support.html
{% load static %}

<!DOCTYPE html>
<html>
        <head>
            <meta http-equiv="content-type" content="text/html; charset=utf-8">
            <title>ArtProject</title>
            <link rel="stylesheet" href="{% static 'css/main_blocks/header_and_footer.css' %}">
            <link rel="stylesheet" href="{% static 'css/main_blocks/sidebar_and_content.css' %}">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa">
        </head>
        <body>
            <div class="container">
                <header class="header">
                    <div class="header_block-logo">
                        <a href="/" class="header_link"><img src="{% static 'img/logo.png' %}" class="link_img"></a>
                    </div>

                    <div class="header_block-navigation-bar">
                      <nav class="header_navigation">
                          <a href="/" class="navigation_a">Main</a>
                          {% if user.is_authenticated %}
                            {% if user.is_staff %}
                              <a href="/add/" class="navigation_a">Add object</a>
                              <a href="/admin/" class="navigation_a">Admin Panel</a>
                            {% endif %}
                            <a href="/personalpage/" class="navigation_a">Personal Page</a>
                          {% else %}
                            <a href="/login/" class="navigation_a">Log In</a>
                            <a href="/registration/" class="navigation_a">Sing Up</a>
                          {% endif %}
                          <a href="/support/" class="navigation_a">Support</a>
                      </nav>
                    </div>
                </header>

                <h1 style="text-align: center;">If you have some problem write me - oleksandr.sokolov10010@gmail.com</h1>
            </div>
        </body>
</html>