config/urls.py
from art.views import (
    add_new_art_object,
    current_page_for_obj,
    delete_art_object,
    show_all_from_art_model
)
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from search.views import Search
from user.views import (
    change_email,
    change_password,
    change_portfolio_page,
    change_portfolio_picture,
    have_not_permission,
    register,
    success_change,
    support,
    user_login,
    user_logout,
    user_personal_page,
)


urlpatterns = [
    path('add/', add_new_art_object, name='add'),
    path('admin/', admin.site.urls, name='admin'),
    path('art/<str:object_id>/', current_page_for_obj, name='current_page_for_obj'),
    path('art/delete/<str:object_id>/', delete_art_object, name='delete'),
    path('personalpage/changeimg/', change_portfolio_picture, name='change_portfolio_picture'),
    path('personalpage/changeemail/', change_email, name='change_email'),
    path('personalpage/changepassword/', change_password, name='change_password'),
    path('personalpage/changepage/', change_portfolio_page, name='change_portfolio_page'),
    path('personalpage/logout/', user_logout, name='user_logout'),
    path('personalpage/success', success_change, name='success_change'),
    path('personalpage/', user_personal_page, name='personal_page'),
    url(r'^login/$', user_login, name='login'),
    url(r'^registration/$', register, name='register'),
    path('permissionerror/', have_not_permission, name='have_not_permission'),
    path('support/', support, name='support'),
    path('search/', Search.as_view(), name = 'search'),
    path('', show_all_from_art_model, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

art/models.py
from django.db import models


class Art(models.Model):
	''' Art model '''

	name = models.CharField(max_length=50, verbose_name='Name', unique=True)
	content = models.TextField(null=True, blank=True, verbose_name='Content')
	img = models.ImageField(verbose_name='Image')

	def __srt__(self):
		return self.name

art/forms.py
from .models import Art
from django import forms


class AddArtForm(forms.ModelForm):
    ''' Form for create a new Art object '''

    class Meta():
        model = Art
        fields = '__all__'

art/views.py
from .services.art_services import (
	take_info_about_object_and_delete,
	take_info_about_object_and_save,
	show_all_objects_from_art_model,
	show_current_object_from_art_model,
)
from django.contrib.admin.views.decorators import staff_member_required


def show_all_from_art_model(request):
	''' Controller for showing the objects on a page '''

	show_objects = show_all_objects_from_art_model(request)

	return show_objects

def current_page_for_obj(request, object_id):
	''' Controller for showing the current object on a page '''

	show_corrent_object = show_current_object_from_art_model(request, object_id)

	return show_corrent_object

@staff_member_required(login_url='/permissionerror/')
def add_new_art_object(request):
	''' Controller for save new object '''

	add_info = take_info_about_object_and_save(request)

	return add_info

@staff_member_required(login_url='/permissionerror/')
def delete_art_object(request, object_id):
	''' Controller for delete current object '''

	delete_object = take_info_about_object_and_delete(request, object_id)

	return delete_object

art/templates/add_new_art_object.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/registration_style.css' %}">
    <title>ArtProject</title>
  </head>

  <body>

    <form enctype = "multipart/form-data" method="POST" class="form">
      {% csrf_token %}

      <h1 class="form-title">Add new info</h1>

      <div class="form-group">
        <input type="text" name="name" required maxlength="50" class="form-input" placeholder=" " id="id_name">
        <label class="form-lable">Name</label>
      </div>

      <div class="form-group">
        <textarea type="text" name="content" required cols="40" rows="10" class="form-input" placeholder=" " id="id_content"></textarea>
        <label class="form-lable">Content</label>
      </div>

      <div class="form-pic">
        <label class="form-table">Image</label>
        <input type="file" name="img" accept="image/*" required id="id_img" style="margin-bottom:25px;">
      </div>

      <button type="submit" name="" value="Add" class="form-button">Add</button>

    </form>
  </body>

</html>

art/templates/current.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>{{ current_object.name }}</title>
    <link rel="stylesheet" href="{% static 'css/main_blocks/current_object.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa">
  </head>
  <body>
    <div class="container">

      <a href="/" class="home-button">Main Page</a>

      <header class="header">
        <img class="header_img" src="{{ current_object.img.url }}">
      </header>

      <article class="content">
        <div class="content_all-info">
          <h1 class="all_info_title">Story about this art</h1>
          <p class="all_info-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
          <p class="all_info-text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
          <p class="all_info-text">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
          <p class="all_info-text">Nullam posuere varius fermentum. Curabitur bibendum posuere convallis. Aenean fringilla, leo non laoreet malesuada, nibh libero finibus orci, quis pharetra justo nisi eu ex. Suspendisse nec ligula aliquet justo euismod gravida. Donec ullamcorper posuere laoreet. Cras ex neque, tincidunt nec gravida ut, mattis at odio. Praesent volutpat iaculis interdum. Maecenas pellentesque rutrum vehicula.</p>
          <p class="all_info-text">Aenean ut gravida neque, nec volutpat felis. Nunc iaculis a arcu eu blandit. Aliquam ante ligula, malesuada tempor diam eleifend, egestas iaculis odio. Quisque tempor sapien id luctus imperdiet. Nulla dui massa, commodo eget augue sit amet, semper mollis ligula. Nunc efficitur porttitor interdum. Etiam nec augue vitae turpis pharetra mattis. Suspendisse sodales maximus posuere. Nulla tincidunt neque sit amet magna viverra, eget sollicitudin lorem interdum.</p>
          <p class="all_info-text">Suspendisse euismod nunc vitae arcu lobortis, et aliquam nisi convallis. Nulla fermentum eros in nibh mollis, a dignissim lorem interdum. Aenean non magna euismod, rhoncus enim iaculis, tristique lectus. Curabitur efficitur purus posuere urna blandit, at finibus massa condimentum. Nam est libero, laoreet ut tempor eu, convallis eget lacus. Praesent elementum vulputate maximus. Proin in pharetra velit. Ut sodales sapien dictum feugiat tempor. Morbi tristique orci sit amet orci elementum varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi auctor sapien eget felis porttitor, at aliquet nulla pretium. Integer vel lobortis mauris. Proin volutpat ligula nec turpis consequat, eu mollis sem suscipit. Ut nec commodo nulla, ut egestas arcu. Donec quis semper leo.</p>
          <p class="all_info-text">Morbi accumsan magna eget lacinia tincidunt. Quisque pretium malesuada erat ut commodo. Aenean scelerisque finibus urna non tempus. Fusce quis diam sed purus finibus bibendum eu vel nibh. Mauris eleifend ligula venenatis pretium varius. Donec tincidunt vel diam dictum posuere. Donec mollis sapien ac condimentum consequat. Etiam elementum enim vitae magna tincidunt, sed viverra tortor blandit. Nulla nisl nisi, sollicitudin sed sagittis at, ornare at mi. Donec a pulvinar magna, ac lacinia erat. Ut ut ligula risus.</p>
        </div>

        <div class="content_short-info">
          <h1>{{ current_object.name }}</h1>
          <div class="short-info_about">
            <p>Size:</p>
            <p>Lorem Ipsum</p>

            <p>Type:</p>
            <p>Lorem Ipsum</p>

            <p>From 'World':</p>
            <p>Lorem Ipsum</p>
          </div>
          {% if user.is_authenticated %}
            <a class="short-info_download-object" href="{{ current_object.img.url }}">Link for Download</a>
          {% else %}
            <p>For download the picture you have to be a logged in</p>
            <a class="short-info_download-object" href="/login/">Login</a>
          {% endif %}

          {% if user.is_staff %}
            <a class="short-info_delete-object" href="/art/delete/{{ current_object.pk }}/">Delete object</a>
          {% endif %}
        </div>
      </article>

      <footer class="footer">

      </footer>

    </div>
  </body>
</html>

art/templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
        <head>
            <meta http-equiv="content-type" content="text/html; charset=utf-8">
            <title>ArtProject</title>
            <link rel="stylesheet" href="{% static 'css/main_blocks/header_and_footer.css' %}">
            <link rel="stylesheet" href="{% static 'css/main_blocks/sidebar_and_content.css' %}">
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Comfortaa">
        </head>
        <body>
            <div class="container">
                <header class="header">
                    <div class="header_block-logo">
                        <a href="/" class="header_link"><img src="{% static 'img/logo.png' %}" class="link_img"></a>
                    </div>

                    <div class="header_block-navigation-bar">
                        <nav class="header_navigation">
                            <a href="/" class="navigation_a">Main</a>
                            {% if user.is_authenticated %}
                              {% if user.is_staff %}
                                <a href="/add/" class="navigation_a">Add object</a>
                                <a href="/admin/" class="navigation_a">Admin Panel</a>
                              {% endif %}
                              <a href="/personalpage/" class="navigation_a">Personal Page</a>
                            {% else %}
                              <a href="/login/" class="navigation_a">Log In</a>
                              <a href="/registration/" class="navigation_a">Sing Up</a>
                            {% endif %}
                            <a href="/support/" class="navigation_a">Support</a>
                        </nav>
                    </div>
                </header>

                <article class="content">
                  <form action="{% url 'search' %}" method="get" class="search_form">
                    <input type="search" placeholder="Enter the name" name="q" class="form_control" required="">
                  </form>

                  <div class="content_all-objects">
                    {% for object in page_obj %}
                      <div class="all-objects_object-block">
                        <a href="/art/{{ object.pk }}/">
                          <img src="{{ object.img.url }}" class="object-block_img">
                        </a>
                        <a href="/art/{{ object.pk }}/" class="object-block_title">{{ object.name }}</a>
                      </div>
                    {% endfor %}
                  </div>

                  <div class="pagination">
                    <span class="step-links">
                      {% if page_obj.has_previous %}
                        <a href="?page=1" class="step-links_link">[ first ]</a>
                        <a href="?page={{ page_obj.previous_page_number }}" class="step-links_link">[ previous ]</a>
                      {% endif %}

                      <span class="current">
                        [-- page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} --]
                      </span>

                      {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" class="step-links_link">[ next ]</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}" class="step-links_link">[ last ]</a>
                      {% endif %}
                    </span>
                  </div>
                </article>

                <aside class="sidebar">
                    <div class="sidebar_block">
                      <h1 class="block_h1">Some info about site or info</h1>
                    </div>

                    <div class="sidebar_block">
                      <h1 class="block_h1">Some info about site or info</h1>
                    </div>
                </aside>
            </div>
        </body>
</html>